// SPDX-License-Identifier: GPL-3.0-or-later
// Created by Romain on 14/09/2020.

#ifndef ROMAINOS_TEXTCOLORMODES_H
#define ROMAINOS_TEXTCOLORMODES_H

#define FG_BLACK 0x00
#define FG_BLUE 0x01
#define FG_GREEN 0x02
#define FG_CYAN 0x03
#define FG_RED 0x04
#define FG_MAGENTA 0x05
#define FG_BROWN 0x06
#define FG_LIGHTGRAY 0x07
#define FG_DARKGRAY 0x08
#define FG_LIGHTBLUE 0x09
#define FG_LIGHTGREEN 0x0a
#define FG_LIGHTCYAN 0x0b
#define FG_LIGHTRED 0x0c
#define FG_LIGHTMAGENTA 0x0d
#define FG_YELLOW 0x0e
#define FG_WHITE 0x0f

#define BG_BLACK 0x00
#define BG_BLUE 0x10
#define BG_GREEN 0x20
#define BG_CYAN 0x30
#define BG_RED 0x40
#define BG_MAGENTA 0x50
#define BG_BROWN 0x60
#define BG_LIGHTGRAY 0x70

#define BG_BLINKINGBLACK 0x80
#define BG_BLINKINGBLUE 0x90
#define BG_BLINKINGGREEN 0xa0
#define BG_BLINKINGCYAN 0xb0
#define BG_BLINKINGRED 0xc0
#define BG_BLINKINGMAGENTA 0xd0
#define BG_BLINKINGYELLOW 0xe0
#define BG_BLINKINGWHITE 0xf0

#define FG_DEFAULT FG_WHITE
#define BG_DEFAULT BG_BLUE

#endif //ROMAINOS_TEXTCOLORMODES_H
